config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "registrations"}
  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 resources :news
 root :to => "news#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/news.rb
class News < ApplicationRecord
has_many :news_photos
belongs_to :user
end

app/models/news_photo.rb
class NewsPhoto < ApplicationRecord
	belongs_to :news

	has_attached_file :image, styles: { medium: "229x319>", thumb: "100x100>" }
  	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many  :news
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
before_action :set_news, only: [:show, :edit, :update]
before_action :authenticate_user!, except: [:show, :index ]
def index
# @news = News.all(:order => "created_at DESC")
# @news = News.all
# @news = News.all(:page => params[:news],:per_page => 10)
@news = News.paginate(:page => params[:page],  :per_page => 12).order('id DESC')

end
def new
if current_user.state == true
  @news = News.new
 else
  flash[:error] = "your account has not been activated"
  redirect_to root_path
 end

end

 def show
 @news_photos = @news.news_photos
 end


  def create
    @news = News.new(news_params)
    if @news.save
      if params[:images]
        params[:images].each do |image|
          @news.news_photos.create(image: image)
        end
      end

      @news_photos = @news.news_photos
      redirect_to edit_news_path(@news), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
     @news_photos = @news.news_photos
  end

   def update
      if @news.update(news_params)
      if params[:images]
        params[:images].each do |image|
          @news.news_photos.create(image: image)
        end
      end
      redirect_to edit_news_path(@news), notice: "Updated..."
    else
      render :edit
    end
  end

  
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_path }
     # format.json { head :no_content }
   end
 end

  
  def destroy
    @news = News.find(params[:id])
    @news.destroy

    respond_to do |format|
      format.html { redirect_to news_index_path }
     # format.json { head :no_content }
   end
 end


   
private
  def set_news
    @news = News.find(params[:id])
  end 

def news_params
    params.require(:news).permit( :title, :description, :category, :keywords, :user_id, :email, :user_name)
  end



end

app/controllers/news_photos_controller.rb
class NewsPhotosController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

#  before_action :one_user_registered?, only: [:new, :create]


  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end



  def one_user_registered?
    if ((User.count == 1) & (user_signed_in?))
      redirect_to root_path
    elsif User.count == 1
      redirect_to new_user_session_path
    end  
  end


private

  def sign_up_params
    params.require(:user).permit(:user_name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit( :email, :password, :password_confirmation, :current_password)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
    @news = News.all
  end

  def show
    @user = User.find(params[:id])
    #my_model = Model.find(123)
     @role_id = User.roles[@user.role] 
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role, :state)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/news_photos_helper.rb
module NewsPhotosHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-dismissible alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
	  <li><%= link_to  edit_user_registration_path do %><%= current_user.email %><% end %></li>
    <li><%= link_to "List Your News", new_news_path %></li>
    <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  	<li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  	
<% else %>
  	<li><%= link_to 'News', news_index_path %></li>
  	<li><%= link_to 'Sign in', new_user_session_path %></li>
  	<li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li><%= link_to 'Users', users_path %></li>
    <li><%= link_to 'News', news_index_path %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <div id="fh5co-offcanvas">
    <a href="#" class="fh5co-close-offcanvas js-fh5co-close-offcanvas"><span><i class="icon-cross3"></i> <span>Close</span></span></a>
    <div class="fh5co-bio">
      <figure>
        <img src="/assets/person1.jpg" alt="Free HTML5 Bootstrap Template" class="img-responsive">
      </figure>
      <h3 class="heading">About Me</h3>
      <h2>Emily Tran Le</h2>
      <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. </p>
      <ul class="fh5co-social">
        <li><a href="#"><i class="icon-twitter"></i></a></li>
        <li><a href="#"><i class="icon-facebook"></i></a></li>
        <li><a href="#"><i class="icon-instagram"></i></a></li>
      </ul>
    </div>

    <div class="fh5co-menu fh5co-bio">
      <div class="fh5co-box">
        <h3 class="heading">Categories</h3>
        <ul>
          <!-- li menus satrting -->
          <%= render 'layouts/nav_links_for_auth' %>
          <!-- li menus ending -->
        </ul>
      </div>
      <!--div class="fh5co-box">
        <h3 class="heading">Search</h3>
        <form action="#">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Type a keyword">
          </div>
        </form>
      </div-->
    </div>
  </div>
  <!-- END #fh5co-offcanvas -->
  <header id="fh5co-header">
    
    <div class="container-fluid">

      <div class="row">
        <a href="#" class="js-fh5co-nav-toggle fh5co-nav-toggle"><i></i></a>
        <ul class="fh5co-social">
          <li><a href="#"><i class="icon-twitter"></i></a></li>
          <li><a href="#"><i class="icon-facebook"></i></a></li>
          <li><a href="#"><i class="icon-instagram"></i></a></li>
        </ul>
        <div class="col-lg-12 col-md-12 text-center">
          <h1 id="fh5co-logo"><a href="/">True Observer <sup>TM</sup></a></h1>
        </div>

      </div>
    
    </div>

  </header>
  <!-- END #fh5co-header -->
       
       
      

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', page_path('about') %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>

	    <meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>True | Observer</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
	    <%= csrf_meta_tags %>

	    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	    <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
		<link rel="shortcut icon" href="favicon.ico">
		<!-- Google Fonts -->
		<link href='http://fonts.googleapis.com/css?family=Playfair+Display:400,700,400italic|Roboto:400,300,700' rel='stylesheet' type='text/css'>
		<!-- Animate -->
		<link rel="stylesheet" href="/assets/animate.css">
		<!-- Icomoon -->
		<link rel="stylesheet" href="/assets/icomoon.css">
		<!-- Bootstrap  -->
		<link rel="stylesheet" href="/assets/bootstrap.css">

		<link rel="stylesheet" href="/assets/style.css">


		<!-- Modernizr JS -->
		<script src="/assets/modernizr-2.6.2.min.js"></script>

  	</head>
  	<body>
		<%= render 'layouts/navigation' %>
    	<%= render 'shared/message' %>
    		<%= yield %>
    	<%= render 'shared/footer' %>
   	</body>
  	<!-- jQuery -->
	<script src="/assets/jquery.min.js"></script>
	<!-- jQuery Easing -->
	<script src="/assets/jquery.easing.1.3.js"></script>
	<!-- Bootstrap -->
	<script src="/assets/bootstrap.min.js"></script>
	<!-- Waypoints -->
	<script src="/assets/jquery.waypoints.min.js"></script>
	<!-- Main JS -->
	<script src="/assets/main.js"></script>
</html>

app/views/news/_form.html.erb
<link type="text/css" rel="stylesheet" href="/assets/jquery-te-1.4.0.css">
<script type="text/javascript" src="http://code.jquery.com/jquery.min.js" charset="utf-8"></script>
<script type="text/javascript" src="/assets/jquery-te-1.4.0.min.js" charset="utf-8"></script>
<style>
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    text-align: right;
    opacity: 0;
    background: #6dae4e;
    cursor: inherit;
    display: block;
}
</style>
<div class="row">
  <div class="col-md-8 col-md-offset-2">
    <%= form_for @news, :html => { :class => 'form-horizontal', multipart: true } do |f| %>
        <div class="row">
          <div class="col-md-12">
            <label>Category</label>
              <div class="form-group">
                <%= f.select :category, [["Sports","Sports"], ["Entertainment","Entertainment"], ["National","National"],
                                ["International","International"],["Arts","Arts"],], {id: 'category', prompt: 'Select...'}, :required => false, class: 'form-control' %>
              </div>                  
          </div>
            </div> 
         <%= f.hidden_field :user_id, value: current_user.id %>
         <%= f.hidden_field :email, value: current_user.email %>       
         <%= f.hidden_field :user_name, value: current_user.user_name %>
        

        <div class="row">
          <div class="col-md-12">
            <%= f.label :description, :class => 'control-label' %>
            <div class="form-group">
              <%= f.text_area :description, :class => 'jqte-test form-control' %>
            </div>
          </div>  
        </div>
       
        <div class="row">
          <div class="col-md-12">
            <%= f.label :title, :class => 'control-label' %>
            <div class="form-group">
              <%= f.text_field :title, :class => 'form-control' %>
            </div>  
          </div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <%= f.label :keywords, :class => 'control-label' %>
            <div class="form-group">
              <%= f.text_field :keywords, :class => 'form-control' %>
            </div>
          </div>  
        </div>  

        <div class="row">
          <div class="col-md-12">
            <label>Upload Image</label>
            <div class="form-group">
              <span class="btn btn-success btn-file">
                  <i class="fa fa-cloud-upload fa-lg"></i> Upload Photos
                    <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>    
            </div>
          </div>  
        </div>

        <div class="row">
          <div class="col-md-6 col-md-offset-4">
            <%= f.submit nil, :class => 'btn btn-info' %>
          </div>
        </div>  
    <% end %>
  </div>
</div>    

<script>
  $('.jqte-test').jqte();
  
  // settings of status
  var jqteStatus = true;
  $(".status").click(function()
  {
    jqteStatus = jqteStatus ? false : true;
    $('.jqte-test').jqte({"status" : jqteStatus})
  });
</script>

app/views/news/edit.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/news/index.html.erb
<link rel="stylesheet" type="text/css" href="/assets/pagination.css">
<link rel="stylesheet" type="text/css" href="/assets/hover-effect.css">
<style type="text/css">
	figure img
	{
		width: 100%;
		height: 319px;
	}
	.fh5co-article-title
	{
		white-space: nowrap; 
	    width: 100%; 
	    overflow: hidden;
	    text-overflow: ellipsis; 
	   
	}
	
	.posted-view
	{
		color: #fff;
	}

</style>
<div class="container-fluid">
		<!--%= link_to "News", news_index_path, class:"sidebar-link active"%-->
		<!--div class="panel-heading" style="background-color:#6dae4e;">
			News(<%= @news.length %>)
		</div-->
		<div class="row fh5co-post-entry">
			<% @news.each do |news| %>
			
				<article class="col-lg-4 col-md-4 col-sm-4 col-xs-6 col-xxs-12 animate-box">
					<div class="hovereffect">
						<figure>
							<%= link_to news do %>
							<%= image_tag news.news_photos[0].image.url if news.news_photos.length > 0 %>
							<% end %>
						</figure>
						<% if user_signed_in? %>
							<% if current_user.id == news.user.id || current_user.admin? %>
								<div class="overlay">
									<% if news.user_name.present? %>
					                	<h3 class="posted-view">Posted By <%= news.user_name %></h3>
					                <% else %>
					                	<h3>Posted By True Observer</h3>	
					                <% end %>	
									<%= link_to "Edit", edit_news_path(news), class: "info" %>
									<%= link_to 'Delete', news_path(news), :method => 'delete', data: {confirm: "Are you sure?"}, :class => 'info' %><br>
									<%= link_to "Qucik View", news_path(news), class: "info" %>
								</div>
							<% end %>	
			            <% else %>
			            	<div class="overlay">
			            		<% if news.user_name.present? %>
				                	<h3>Posted By <%= news.user_name %></h3>
				                <% else %>
				                	<h3>Posted By True Observer</h3>
				                <% end %>	 
								<%= link_to "Qucik View", news_path(news), class: "info" %>
				            </div>
			            <% end %>
					</div>
					<%= link_to news do %>
					<span class="fh5co-meta"><%=  news.category %></span>
					<h2 class="fh5co-article-title"><%= news.title %></h2>
					<!--% if current_user.id == news.user.id || current_user.admin? %>
                    	<!--%= link_to "Edit", edit_news_path(news), class: "btn btn-mini" %>
                    	<!--%= link_to 'Delete', news_path(news), :method => 'delete', data: {confirm: "Are you sure?"}, :class => 'btn btn-mini' %>
                    <!--% end %-->
                                        <% if news.user_name.present? %>
					<span class="fh5co-meta">Posted By <%= news.user_name %></span>
                                        <% else %>
                                        <p> Posted By: True Observer </p>
                                         <% end %> 
                                

					<span class="fh5co-meta fh5co-date"> <%= news.created_at.to_time.strftime("%B %d, %Y") %></span>
					<% end %>
				</article>
			
			<% end %>
		</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-12">
			<div class="digg_pagination">
			    <div class="page_info">
			      <%= page_entries_info @posts %>
			    </div>
			    <center>
			    <div class="paginate-width" align="center">
    				<%= will_paginate @posts, :container => false %>
    			</div>
    			</center>		
  			</div>
		</div>
	</div>
</div>			

app/views/news/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

app/views/news/show.html.erb
<a href="#" class="fh5co-post-prev"><span><i class="icon-chevron-left"></i> Prev</span></a>
<a href="#" class="fh5co-post-next"><span>Next <i class="icon-chevron-right"></i></span></a>
<div class="container-fluid">
    <div class="row fh5co-post-entry single-entry">
      <article class="col-lg-8 col-lg-offset-2 col-md-8 col-md-offset-2 col-sm-8 col-sm-offset-2 col-xs-12 col-xs-offset-0">
        <% if @news_photos %>
          <% @news_photos.each do |news_photo| %>
            <figure class="animate-box">
              <%= image_tag news_photo.image.url(), class:"img-responsive"%>
            </figure>
          <% end %>
        <% end %>    
        <span class="fh5co-meta animate-box"><%= @news.category %></span>
        <h2 class="fh5co-article-title animate-box"><%= @news.title %></h2>
        <span class="fh5co-meta fh5co-date animate-box">March 6th, 2016</span>
        
        <div class="col-lg-12 col-lg-offset-0 col-md-12 col-md-offset-0 col-sm-12 col-sm-offset-0 col-xs-12 col-xs-offset-0 text-left content-article">
          <div class="row">
            <div class="col-lg-12 cp-r animate-box">
              <p><%= @news.description %></p>
            </div>
            <!--div class="col-lg-4 animate-box">
              <div class="fh5co-highlight right">
                <h4>Highlight</h4>
                <p>Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia</p>
              </div>
            </div-->
          </div>

          <!--div class="row rp-b">
            <div class="col-md-12 animate-box">
              <blockquote>
                <p>&ldquo;She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove &rdquo; <cite>&mdash; Jean Smith</cite></p>
              </blockquote>
            </div>
          </div>

          <div class="row rp-b">
            <div class="col-lg-6 col-md-12 animate-box">
              <figure>
                <img src="images/pic_1.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
                <figcaption>This is a sweet image caption. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</figcaption>
              </figure>
            </div>
            <div class="col-lg-6 col-md-12 cp-l animate-box">
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. </p>

              <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>

              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large <a href="#">language</a> ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>

          <div class="row rp-b">
            <div class="col-lg-6 col-lg-push-6 col-md-12 col-md-push-0 animate-box">
              <figure>
                <img src="images/pic_4.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
                <figcaption>This is a sweet image caption. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</figcaption>
              </figure>
            </div>
            <div class="col-lg-6 col-lg-pull-6 col-md-12 col-md-pull-0 cp-r animate-box">
              <p>Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar. The Big Oxmox advised her not to do so, because there were thousands of bad Commas, wild Question Marks and devious Semikoli, but the Little Blind Text didn’t listen. </p>

              <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>

              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large <a href="#">language</a> ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
            </div>
          </div>

          <div class="row">
            <div class="col-md-12 animate-box">
              <h2>Pointing has no control about the blind texts</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large <a href="#">language</a> ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
            </div>
            <div class="col-md-4 animate-box">
              <figure>
                <img src="images/pic_5.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
                <figcaption>This is a sweet image caption. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</figcaption>
              </figure>
            </div>
            <div class="col-md-4 animate-box">
              <figure>
                <img src="images/pic_6.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
                <figcaption>This is a sweet image caption. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</figcaption>
              </figure>
            </div>
            <div class="col-md-4 animate-box">
              <figure>
                <img src="images/pic_7.jpg" alt="Free HTML5 Bootstrap Template by FREEHTML5.co" class="img-responsive">
                <figcaption>This is a sweet image caption. Far far away, behind the word mountains, far from the countries Vokalia and Consonantia</figcaption>
              </figure>
            </div>
            <div class="col-md-12 animate-box">
              <h2>Pointing has no control about the blind texts</h2>
              <p>Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large <a href="#">language</a> ocean. A small river named Duden flows by their place and supplies it with the necessary regelialia. It is a paradisematic country, in which roasted parts of sentences fly into your mouth.</p>
              <p>She packed her seven versalia, put her initial into the belt and made herself on the way. When she reached the first hills of the Italic Mountains, she had a last view back on the skyline of her hometown Bookmarksgrove, the headline of Alphabet Village and the subline of her own road, the Line Lane. Pityful a rethoric question ran over her cheek, then she continued her way.</p>
            </div>
          </div-->
          
          
        </div>
      </article>
    </div>
  </div>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/shared/_footer.html.erb
<footer id="fh5co-footer">
		<p><small>&copy; 2016. True Observer  Demo Images: <a href="http://unsplash.com/" target="_blank">Unsplash</a></small></p>
	</footer>


app/views/shared/_message.html.erb
<% unless flash.empty? %>
        <script type="text/javascript">
                <% flash.each do |f| %>
                        <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
                        toastr['<%= type %>']('<%= f[1] %>')
                <% end %>
        </script>
<% end %>


app/views/users/_user.html.erb
<td><%= link_to user.user_name, user %></td>
<td>
  <%= link_to user.email, user %>
</td>
<%= form_for(user) do |f| %>
   	<td><%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %></td>
   	<td><%= f.label "active" %>
       <%= f.check_box :state %>
    </td>
    <td><%= f.submit 'Change', :class => 'button-xs' %></td>
 
  <% end %>
<td>
  	<%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="table-responsive">
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>User Name</th>
            <th>Role</th>
            <th>State</th>
            <th colspan="2">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>    
        </tbody>
      </table>
    </div>
  </div>
</div>

  

app/views/visitors/index.html.erb
<h3>Welcome</h3>
<p><%= link_to 'Users:', users_path %> <%= User.count %> registered</p>